#
# Copyright 2019 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


# This file is generated by device/pantech/ef52l/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/pantech/ef52l/proprietary/lib/libsensor1.so:system/lib/libsensor1.so \
    vendor/pantech/ef52l/proprietary/lib/libsensor_reg.so:system/lib/libsensor_reg.so \
    vendor/pantech/ef52l/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/pantech/ef52l/proprietary/lib/hw/sensors.msm8960.so:system/lib/hw/sensors.msm8960.so \
    vendor/pantech/ef52l/proprietary/lib/hw/sensors_native_hal.so:system/lib/hw/sensors_native_hal.so \
    vendor/pantech/ef52l/proprietary/lib/hw/sensors_qcom.so:system/lib/hw/sensors_qcom.so \
    vendor/pantech/ef52l/proprietary/lib/hw/lights.msm8960.so:system/lib/hw/lights.msm8960.so
